language: node_js
node_js:
  - '12'

install:
  - npm install
cache:
  directories:
    - 'node_modules'

script:
  - npm run lint
  - npm run test

after_success:
  - nyc report --reporter=text-lcov | coveralls